---
apiVersion: v1
kind: Service
metadata:
  name: fake-similarweb
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 9081
    protocol: TCP
  selector:
    app: fake-similarweb
